const ActionTypes = {
  RECORD_FETCH_REQUEST: 'RECORD_FETCH_REQUEST',
  RECORD_FETCH_SUCCEEDED: 'RECORD_FETCH_SUCCEEDED',
  RECORD_FETCH_FAILED: 'RECORD_FETCH_FAILED',

  RECORD_TODAY_FETCH_REQUEST: 'RECORD_TODAY_FETCH_REQUEST',
  RECORD_TODAY_FETCH_SUCCEEDED: 'RECORD_TODAY_FETCH_SUCCEEDED',
  RECORD_TODAY_FETCH_FAILED: 'RECORD_TODAY_FETCH_FAILED'
};

export default ActionTypes;